import type { NotebookPageEngine, NotebookPageOptions } from './notebook-page-engine.ts';
import { cellName, cellPosition, columnName, displayCell, normalizeSheet, parseDelimited, reshapeSheet, SHEET_COLS, SHEET_ROWS, sheetEvaluator, writeDelimited, type SheetCell } from '../../lib/notebook-spreadsheet.ts';
import '../../styles/notebook-spreadsheet.css';

export function createSpreadsheetPage(options: NotebookPageOptions): NotebookPageEngine {
  let state = normalizeSheet(null), anchor: [number, number] = [0, 0], active: [number, number] = [0, 0];
  let editing: HTMLInputElement | null = null, dragging = false, destroyed = false;
  const undo: string[] = [], redo: string[] = []; const controller = new AbortController(); const signal = controller.signal;
  const element = document.createElement('section'); element.className = 'nb-sheet'; element.setAttribute('aria-label', 'Spreadsheet');
  const toolbar = document.createElement('div'); toolbar.className = 'nb-sheet-tools'; toolbar.setAttribute('aria-label', 'Spreadsheet tools');
  const formulaRow = document.createElement('div'); formulaRow.className = 'nb-sheet-formula';
  const address = document.createElement('input'); address.className = 'nb-sheet-address'; address.setAttribute('aria-label', 'Go to cell'); address.title = 'Cell address, for example B3';
  const formula = document.createElement('input'); formula.setAttribute('aria-label', 'Cell value or formula'); formula.placeholder = 'Value or formula, e.g. =SUM(A1:A10)'; formula.maxLength = 10000; formula.spellcheck = false;
  const scroller = document.createElement('div'); scroller.className = 'nb-sheet-scroll';
  const grid = document.createElement('table'); grid.className = 'nb-sheet-grid'; grid.setAttribute('role', 'grid'); grid.setAttribute('aria-label', 'Spreadsheet cells'); scroller.append(grid);
  const status = document.createElement('div'); status.className = 'nb-sheet-status'; status.setAttribute('role', 'status'); status.setAttribute('aria-live', 'polite');
  formulaRow.append(address, formula); element.append(toolbar, formulaRow, scroller, status);
  function button(label: string, action: () => void) { const b = document.createElement('button'); b.type = 'button'; b.textContent = label; b.title = label; b.addEventListener('click', action, { signal }); toolbar.append(b); return b; }
  function select(label: string, values: [string, string][], change: (value: string) => void) { const el = document.createElement('select'); el.setAttribute('aria-label', label); el.title = label; for (const [value, text] of values) { const option = document.createElement('option'); option.value = value; option.textContent = text; el.append(option); } el.addEventListener('change', () => change(el.value), { signal }); toolbar.append(el); return el; }
  function report(message: string) { status.textContent = message; }
  function change(work: () => void) { const previous = JSON.stringify(state); try { work(); if (JSON.stringify(state) !== previous) { undo.push(previous); if (undo.length > 40) undo.shift(); redo.length = 0; render(); options.onChange(); } } catch (error) { state = normalizeSheet(JSON.parse(previous)); render(); report(error instanceof Error ? error.message : 'Unable to change the sheet.'); } }
  function bounds() { return { r0: Math.min(anchor[0], active[0]), r1: Math.max(anchor[0], active[0]), c0: Math.min(anchor[1], active[1]), c1: Math.max(anchor[1], active[1]) }; }
  function eachSelected(work: (name: string) => void) { const b = bounds(); for (let r = b.r0; r <= b.r1; r++) for (let c = b.c0; c <= b.c1; c++) work(cellName(r, c)); }
  function formatSelection(update: Partial<SheetCell>) { change(() => eachSelected(name => { state.cells[name] = { ...state.cells[name], value: state.cells[name]?.value ?? '', ...update }; })); }
  const undoButton = button('Undo', () => history(undo, redo)); const redoButton = button('Redo', () => history(redo, undo));
  function history(from: string[], to: string[]) { finishEdit(); const previous = from.pop(); if (!previous) return; to.push(JSON.stringify(state)); state = normalizeSheet(JSON.parse(previous)); render(); options.onChange(); focusCell(); }
  const bold = button('Bold', () => formatSelection({ bold: !state.cells[cellName(...active)]?.bold }));
  const italic = button('Italic', () => formatSelection({ italic: !state.cells[cellName(...active)]?.italic }));
  const format = select('Number format', [['auto', 'Automatic'], ['text', 'Text'], ['number', 'Number'], ['currency', 'Currency (USD)'], ['percent', 'Percent']], value => formatSelection({ format: value as SheetCell['format'] }));
  const align = select('Cell alignment', [['left', 'Align left'], ['center', 'Align center'], ['right', 'Align right']], value => formatSelection({ align: value as SheetCell['align'] }));
  for (const [key, label, initial] of [['color', 'Text color', '#172033'], ['fill', 'Cell fill', '#ffffff']] as const) { const input = document.createElement('input'); input.type = 'color'; input.value = initial; input.setAttribute('aria-label', label); input.title = label; input.addEventListener('input', () => formatSelection({ [key]: input.value }), { signal }); toolbar.append(input); }
  button('Clear format', () => change(() => eachSelected(name => { if (state.cells[name]) state.cells[name] = { value: state.cells[name].value }; })));
  const structure = select('Rows and columns', [['', 'Rows & columns'], ['row-before', 'Insert row above'], ['row-after', 'Insert row below'], ['column-before', 'Insert column left'], ['column-after', 'Insert column right'], ['row-delete', 'Delete selected rows'], ['column-delete', 'Delete selected columns']], value => {
    if (!value) return; const [axis, op] = value.split('-') as ['row' | 'column', string]; change(() => { const b = bounds(), index = axis === 'row' ? b.r0 : b.c0, end = axis === 'row' ? b.r1 : b.c1; if (op === 'delete') { const size = axis === 'row' ? state.rows : state.cols; if (end - index + 1 >= size) throw new Error('Keep at least one row and column.'); for (let n = end; n >= index; n--) reshapeSheet(state, axis, n, true); } else reshapeSheet(state, axis, op === 'after' ? end + 1 : index, false); }); structure.value = '';
  });
  for (const [axis, label, initial, min, max] of [['column', 'Column width', 120, 50, 600], ['row', 'Row height', 30, 24, 240]] as const) { const input = document.createElement('input'); input.type = 'number'; input.value = String(initial); input.min = String(min); input.max = String(max); input.setAttribute('aria-label', label); input.title = `${label} in pixels`; input.className = 'nb-sheet-size'; input.addEventListener('change', () => { const n = Number(input.value); if (!Number.isFinite(n)) return; change(() => { const b = bounds(), start = axis === 'column' ? b.c0 : b.r0, end = axis === 'column' ? b.c1 : b.r1; for (let i = start; i <= end; i++) state[axis === 'column' ? 'widths' : 'heights'][i] = Math.max(min, Math.min(max, n)); }); }, { signal }); toolbar.append(input); }
  const file = document.createElement('input'); file.type = 'file'; file.accept = '.csv,.tsv,text/csv,text/tab-separated-values'; file.hidden = true; toolbar.append(file);
  button('Import CSV', () => file.click());
  file.addEventListener('change', async () => { const source = file.files?.[0]; if (!source) return; try { if (source.size > 2_000_000) throw new Error('Import is limited to 2 MB.'); const data = parseDelimited(await source.text(), /\.tsv$/i.test(source.name) ? '\t' : ','); if (destroyed) return; paste(data); } catch (error) { report(error instanceof Error ? error.message : 'Could not read this file.'); } file.value = ''; }, { signal });
  button('Export CSV', () => { finishEdit(); const calculate = sheetEvaluator(state); let endRow = 0, endCol = 0; for (const [name, cell] of Object.entries(state.cells)) if (cell.value) { const pos = cellPosition(name)!; endRow = Math.max(endRow, pos[0]); endCol = Math.max(endCol, pos[1]); } const rows = Array.from({ length: endRow + 1 }, (_, r) => Array.from({ length: endCol + 1 }, (_, c) => { const value = String(calculate(cellName(r, c))); return /^[=+@-]/.test(value) && !Number.isFinite(Number(value)) ? `'${value}` : value; })); const url = URL.createObjectURL(new Blob(['\uFEFF', writeDelimited(rows, ',')], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'notebook-sheet.csv'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); });
  button('Formula help', () => report('Formulas: + − * / ^, %, comparisons, SUM, AVERAGE, MIN, MAX, COUNT, COUNTA, ROUND, ABS, IF, AND, OR, NOT. Ranges: A1:B10. Select with Shift or drag; Enter/F2 edits. Imports paste at the active cell. Limit: 200 rows × 52 columns.'));

  function td(row: number, col: number) { return grid.querySelector<HTMLTableCellElement>(`td[data-row="${row}"][data-col="${col}"]`); }
  function focusCell() { td(...active)?.focus({ preventScroll: true }); td(...active)?.scrollIntoView({ block: 'nearest', inline: 'nearest' }); }
  function refreshSelection() {
    const b = bounds(); for (const cell of grid.querySelectorAll<HTMLTableCellElement>('td[data-row]')) { const selected = +cell.dataset.row! >= b.r0 && +cell.dataset.row! <= b.r1 && +cell.dataset.col! >= b.c0 && +cell.dataset.col! <= b.c1; cell.setAttribute('aria-selected', String(selected)); cell.classList.toggle('nb-sheet-active', +cell.dataset.row! === active[0] && +cell.dataset.col! === active[1]); cell.tabIndex = +cell.dataset.row! === active[0] && +cell.dataset.col! === active[1] ? 0 : -1; }
    const name = cellName(...active), cell = state.cells[name]; address.value = name; formula.value = cell?.value ?? ''; format.value = cell?.format ?? 'auto'; align.value = cell?.align ?? 'left'; bold.setAttribute('aria-pressed', String(!!cell?.bold)); italic.setAttribute('aria-pressed', String(!!cell?.italic));
    report(b.r0 === b.r1 && b.c0 === b.c1 ? `${name}${cell?.value.startsWith('=') ? ` · ${cell.value}` : ''}` : `${cellName(b.r0, b.c0)}:${cellName(b.r1, b.c1)} · ${(b.r1 - b.r0 + 1) * (b.c1 - b.c0 + 1)} cells`);
  }
  function move(row: number, col: number, extend = false) { finishEdit(); active = [Math.max(0, Math.min(state.rows - 1, row)), Math.max(0, Math.min(state.cols - 1, col))]; if (!extend) anchor = [...active]; refreshSelection(); focusCell(); }
  function render() {
    editing = null; active = [Math.min(active[0], state.rows - 1), Math.min(active[1], state.cols - 1)]; anchor = [Math.min(anchor[0], state.rows - 1), Math.min(anchor[1], state.cols - 1)];
    const calculate = sheetEvaluator(state); const cols = document.createElement('colgroup'); const cornerCol = document.createElement('col'); cornerCol.style.width = '44px'; cols.append(cornerCol);
    for (let c = 0; c < state.cols; c++) { const col = document.createElement('col'); col.style.width = `${state.widths[c] ?? 120}px`; cols.append(col); }
    const head = document.createElement('thead'), header = document.createElement('tr'), corner = document.createElement('th'); corner.setAttribute('aria-label', 'Select all cells'); corner.dataset.all = 'true'; corner.textContent = ''; header.append(corner);
    for (let c = 0; c < state.cols; c++) { const th = document.createElement('th'); th.scope = 'col'; th.textContent = columnName(c); th.dataset.column = String(c); th.title = `Select column ${columnName(c)}`; header.append(th); } head.append(header);
    const body = document.createElement('tbody'); for (let r = 0; r < state.rows; r++) { const tr = document.createElement('tr'); tr.style.height = `${state.heights[r] ?? 30}px`; const th = document.createElement('th'); th.scope = 'row'; th.textContent = String(r + 1); th.dataset.rowHeader = String(r); th.title = `Select row ${r + 1}`; tr.append(th);
      for (let c = 0; c < state.cols; c++) { const name = cellName(r, c), cell = state.cells[name], value = calculate(name); const el = document.createElement('td'); el.dataset.row = String(r); el.dataset.col = String(c); el.setAttribute('role', 'gridcell'); el.setAttribute('aria-label', `${name}: ${displayCell(cell, value) || 'empty'}`); el.textContent = displayCell(cell, value); el.title = cell?.value ?? ''; el.style.textAlign = cell?.align ?? (typeof value === 'number' ? 'right' : 'left'); if (cell?.bold) el.style.fontWeight = '700'; if (cell?.italic) el.style.fontStyle = 'italic'; if (cell?.color) el.style.color = cell.color; if (cell?.fill) el.style.backgroundColor = cell.fill; if (typeof value === 'string' && value.startsWith('#') && cell?.value.startsWith('=')) el.classList.add('nb-sheet-error'); tr.append(el); } body.append(tr); }
    grid.replaceChildren(cols, head, body); grid.style.width = `${44 + Array.from({ length: state.cols }, (_, i) => state.widths[i] ?? 120).reduce((a, b) => a + b, 0)}px`; grid.setAttribute('aria-rowcount', String(state.rows + 1)); grid.setAttribute('aria-colcount', String(state.cols + 1)); undoButton.disabled = undo.length === 0; redoButton.disabled = redo.length === 0; refreshSelection();
  }
  function setValue(value: string) { const name = cellName(...active); if ((state.cells[name]?.value ?? '') === value) return; change(() => { state.cells[name] = { ...state.cells[name], value: value.slice(0, 10000) }; }); }
  function finishEdit(cancel = false) { if (!editing) return; const input = editing; editing = null; if (!cancel) setValue(input.value); render(); }
  function startEdit(value?: string) { if (editing) return; const cell = td(...active); if (!cell) return; const input = document.createElement('input'); input.className = 'nb-sheet-cell-input'; input.setAttribute('aria-label', `Edit ${cellName(...active)}`); input.maxLength = 10000; input.value = value ?? state.cells[cellName(...active)]?.value ?? ''; input.spellcheck = false; cell.replaceChildren(input); editing = input; input.addEventListener('input', () => { formula.value = input.value; }, { signal }); input.addEventListener('blur', () => finishEdit(), { signal }); input.focus(); if (value === undefined) input.select(); }
  grid.addEventListener('pointerdown', event => { const target = (event.target as HTMLElement).closest<HTMLElement>('td,th'); if (!target || target.contains(editing)) return;
    if (target.dataset.column !== undefined) { finishEdit(); anchor = [0, +target.dataset.column]; active = [state.rows - 1, +target.dataset.column]; refreshSelection(); focusCell(); event.preventDefault(); }
    else if (target.dataset.rowHeader !== undefined) { finishEdit(); anchor = [+target.dataset.rowHeader, 0]; active = [+target.dataset.rowHeader, state.cols - 1]; refreshSelection(); focusCell(); event.preventDefault(); }
    else if (target.dataset.all) { anchor = [0, 0]; active = [state.rows - 1, state.cols - 1]; refreshSelection(); focusCell(); event.preventDefault(); }
    else if (target.dataset.row !== undefined) { move(+target.dataset.row, +target.dataset.col!, event.shiftKey); dragging = true; event.preventDefault(); }
  }, { signal });
  grid.addEventListener('pointerover', event => { if (!dragging) return; const target = (event.target as HTMLElement).closest<HTMLElement>('td[data-row]'); if (!target) return; active = [+target.dataset.row!, +target.dataset.col!]; refreshSelection(); }, { signal });
  document.addEventListener('pointerup', () => { if (dragging) { dragging = false; focusCell(); } }, { signal });
  grid.addEventListener('dblclick', event => { if ((event.target as HTMLElement).closest('td')) startEdit(); }, { signal });
  grid.addEventListener('keydown', event => {
    const mod = event.ctrlKey || event.metaKey;
    if (editing) { if (event.key === 'Escape') { event.preventDefault(); finishEdit(true); focusCell(); } else if (event.key === 'Enter' || event.key === 'Tab') { event.preventDefault(); finishEdit(); move(active[0] + (event.key === 'Enter' ? event.shiftKey ? -1 : 1 : 0), active[1] + (event.key === 'Tab' ? event.shiftKey ? -1 : 1 : 0)); } return; }
    if (mod && event.key.toLowerCase() === 'z') { event.preventDefault(); history(event.shiftKey ? redo : undo, event.shiftKey ? undo : redo); return; }
    if (mod && event.key.toLowerCase() === 'y') { event.preventDefault(); history(redo, undo); return; }
    if (mod && event.key.toLowerCase() === 'a') { event.preventDefault(); anchor = [0, 0]; active = [state.rows - 1, state.cols - 1]; refreshSelection(); return; }
    if (event.key === 'Enter' || event.key === 'F2') { event.preventDefault(); startEdit(); return; }
    if (event.key === 'Backspace' || event.key === 'Delete') { event.preventDefault(); change(() => eachSelected(name => { if (state.cells[name]) state.cells[name].value = ''; })); focusCell(); return; }
    const offsets: Record<string, [number, number]> = { ArrowUp: [-1, 0], ArrowDown: [1, 0], ArrowLeft: [0, -1], ArrowRight: [0, 1], Tab: [0, event.shiftKey ? -1 : 1] };
    if (offsets[event.key]) { event.preventDefault(); const [r, c] = offsets[event.key]; move(active[0] + r, active[1] + c, event.shiftKey && event.key !== 'Tab'); return; }
    if (event.key === 'Home' || event.key === 'End') { event.preventDefault(); move(mod ? event.key === 'Home' ? 0 : state.rows - 1 : active[0], event.key === 'Home' ? 0 : state.cols - 1, event.shiftKey); return; }
    if (!mod && !event.altKey && event.key.length === 1) { event.preventDefault(); startEdit(event.key); }
  }, { signal });
  formula.addEventListener('change', () => setValue(formula.value), { signal });
  formula.addEventListener('keydown', event => { if (event.key === 'Enter') { event.preventDefault(); setValue(formula.value); focusCell(); } if (event.key === 'Escape') { formula.value = state.cells[cellName(...active)]?.value ?? ''; focusCell(); } }, { signal });
  address.addEventListener('keydown', event => { if (event.key !== 'Enter') return; event.preventDefault(); const pos = cellPosition(address.value.trim()); if (!pos || pos[0] >= state.rows || pos[1] >= state.cols) { report('Enter a cell address inside the current sheet.'); return; } move(...pos); }, { signal });
  function paste(rows: string[][]) { const b = bounds(); const width = Math.max(...rows.map(row => row.length)); if (b.r0 + rows.length > SHEET_ROWS || b.c0 + width > SHEET_COLS) { report(`Paste exceeds ${SHEET_ROWS} rows or ${SHEET_COLS} columns. No cells changed.`); return; }
    change(() => { state.rows = Math.max(state.rows, b.r0 + rows.length); state.cols = Math.max(state.cols, b.c0 + width); rows.forEach((row, r) => row.forEach((value, c) => { const name = cellName(b.r0 + r, b.c0 + c); state.cells[name] = { ...state.cells[name], value }; })); anchor = [b.r0, b.c0]; active = [b.r0 + rows.length - 1, b.c0 + width - 1]; }); report(`Pasted ${rows.length} rows × ${width} columns. Undo restores overwritten cells.`); focusCell(); }
  grid.addEventListener('copy', event => { if (editing || !event.clipboardData) return; const b = bounds(); const rows = Array.from({ length: b.r1 - b.r0 + 1 }, (_, r) => Array.from({ length: b.c1 - b.c0 + 1 }, (_, c) => state.cells[cellName(b.r0 + r, b.c0 + c)]?.value ?? '')); event.clipboardData.setData('text/plain', writeDelimited(rows, '\t')); event.preventDefault(); }, { signal });
  grid.addEventListener('cut', event => { if (editing || !event.clipboardData) return; const b = bounds(); const rows = Array.from({ length: b.r1 - b.r0 + 1 }, (_, r) => Array.from({ length: b.c1 - b.c0 + 1 }, (_, c) => state.cells[cellName(b.r0 + r, b.c0 + c)]?.value ?? '')); event.clipboardData.setData('text/plain', writeDelimited(rows, '\t')); event.preventDefault(); change(() => eachSelected(name => { if (state.cells[name]) state.cells[name].value = ''; })); focusCell(); }, { signal });
  grid.addEventListener('paste', event => { if (editing || !event.clipboardData) return; event.preventDefault(); try { paste(parseDelimited(event.clipboardData.getData('text/plain'), '\t')); } catch (error) { report(error instanceof Error ? error.message : 'Unable to paste cells.'); } }, { signal });
  render();
  return { element, load(value) { state = normalizeSheet(value); undo.length = redo.length = 0; anchor = [0, 0]; active = [0, 0]; render(); }, serialize() { const result = structuredClone(state); if (editing) { const name = cellName(...active); result.cells[name] = { ...result.cells[name], value: editing.value }; } return result; }, text() { const calculate = sheetEvaluator(state); return Object.keys(state.cells).filter(name => state.cells[name].value).map(name => `${name}: ${displayCell(state.cells[name], calculate(name))}`).join('\n'); }, focus() { focusCell(); }, destroy() { destroyed = true; controller.abort(); element.remove(); } };
}
