import fs from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import type { Download, BrowserContext, Page } from 'playwright-core';
import { DATA_DIR, getDb } from '../db.ts';
import { getSetting, setSetting } from '../settings.ts';
import { httpUrl } from '../wards.ts';

export const DOWNLOAD_BYTES = 25 * 1024 * 1024;
const ROOT = path.join(DATA_DIR, 'browser-downloads');
const globalDownloads = globalThis as { __fdBrowserDownloads?: Map<string, Promise<void>> };
const active = globalDownloads.__fdBrowserDownloads ?? new Map<string, Promise<void>>();
globalDownloads.__fdBrowserDownloads = active;
export interface BrowserDownload {
  id: string;
  name: string;
  url: string;
  status: 'downloading' | 'ready' | 'failed';
  bytes?: number;
  error?: string;
  at: string;
}
const prefix = (user: number, ward: string) => `browser_download:${user}:${ward}:`;
const filePath = (user: number, ward: string, id: string) => path.join(ROOT, String(user), ward, id);
const keyOf = (user: number, ward: string, id: string) => prefix(user, ward) + id;
const safeName = (name: string) => (name.replace(/[\\/\p{Cc}]/gu, '_').trim() || 'download').slice(0, 180).toWellFormed();

export function listDownloads(user: number, ward: string): BrowserDownload[] {
  return (getDb().prepare('SELECT key,value FROM settings WHERE key GLOB ? ORDER BY updated_at DESC, key DESC LIMIT 100')
    .all(`${prefix(user, ward)}*`) as { key: string; value: string }[]).map(row => {
    const value = JSON.parse(row.value) as BrowserDownload;
    if (value.status === 'downloading' && !active.has(row.key))
      return { ...value, status: 'failed', error: 'Download interrupted. Start it again from the website.' };
    return value;
  });
}

/** Downloads remain on their browser's runtime. Only an explicit Rime import copies a file into a conversation. */
export function captureDownload(user: number, ward: string, download: Download, tempDir: string | undefined,
  notify: (file: BrowserDownload) => void): void {
  const file: BrowserDownload = { id: randomUUID(), name: safeName(download.suggestedFilename()), url: download.url().startsWith('data:') ? '[generated by page]' : download.url().slice(0, 2000), status: 'downloading', at: new Date().toISOString() };
  const key = keyOf(user, ward, file.id);
  const save = () => { setSetting(key, JSON.stringify(file)); notify({ ...file }); };
  // ponytail: one transfer per ward bounds memory/disk monitoring; use per-download CDP tracking if parallel downloads are needed.
  if ([...active.keys()].some(k => k.startsWith(prefix(user, ward))) || listDownloads(user, ward).length >= 100) {
    void download.cancel().catch(() => {});
    notify({ ...file, status: 'failed', error: 'Finish the current download or remove older downloads (100 per browser).' });
    return;
  }
  let expired = false, oversized = false;
  const timer = setTimeout(() => { expired = true; void download.cancel().catch(() => {}); }, 120_000);
  const monitor = tempDir ? setInterval(() => {
    try {
      if (fs.readdirSync(tempDir).some(name => fs.statSync(path.join(tempDir, name)).size > DOWNLOAD_BYTES)) {
        oversized = true;
        void download.cancel().catch(() => {});
      }
    } catch { /* Chromium renames its partial file on completion. */ }
  }, 250) : undefined;
  const pending = Promise.resolve().then(async () => {
    try {
      const stream = await download.createReadStream();
      if (!stream) throw Error('Download returned no file.');
      const chunks: Buffer[] = []; let bytes = 0;
      for await (const chunk of stream) {
        bytes += chunk.length;
        if (bytes > DOWNLOAD_BYTES) { oversized = true; throw Error('Download too large.'); }
        chunks.push(Buffer.from(chunk));
      }
      if (!bytes) throw Error('The downloaded file is empty.');
      const dest = filePath(user, ward, file.id);
      fs.mkdirSync(path.dirname(dest), { recursive: true, mode: 0o700 });
      fs.writeFileSync(dest, Buffer.concat(chunks), { mode: 0o600, flag: 'wx' });
      file.status = 'ready'; file.bytes = bytes;
    } catch (e) {
      file.status = 'failed';
      file.error = oversized ? 'Download exceeds 25 MB.' : expired ? 'Download timed out after two minutes.'
        : `Download failed: ${e instanceof Error ? e.message.split('\n')[0] : 'file unavailable'}`;
    } finally {
      clearTimeout(timer); if (monitor) clearInterval(monitor);
      save();
      active.delete(key);
      await download.delete().catch(() => {});
    }
  });
  active.set(key, pending);
  save();
  void pending.catch(() => {});
}

/** Read through Chromium's authenticated network stack, including PDFs displayed inline.
 * No server fetch/cookie copying: the same browser proxy and credentials apply. */
export function startUrlDownload(user: number, ward: string, context: BrowserContext, page: Page, url: string,
  notify: (file: BrowserDownload) => void): BrowserDownload {
  const href = httpUrl(url);
  if (!href) throw Error('http(s) URLs only');
  if ([...active.keys()].some(k => k.startsWith(prefix(user, ward)))) throw Error('A download is already in progress. Check browser_downloads.');
  if (listDownloads(user, ward).length >= 100) throw Error('Remove older downloads first (100 per browser).');
  const file: BrowserDownload = { id: randomUUID(), name: safeName(new URL(href).pathname.split('/').pop() ?? 'download'), url: href.slice(0, 2000), status: 'downloading', at: new Date().toISOString() };
  const key = keyOf(user, ward, file.id);
  const save = () => { setSetting(key, JSON.stringify(file)); notify({ ...file }); };
  const pending = Promise.resolve().then(async () => {
    let cdp: Awaited<ReturnType<BrowserContext['newCDPSession']>> | undefined;
    let timer: ReturnType<typeof setTimeout> | undefined;
    let handle: string | undefined;
    try {
      cdp = await context.newCDPSession(page);
      timer = setTimeout(() => { void cdp?.detach().catch(() => {}); }, 120_000);
      const { frameTree } = await cdp.send('Page.getFrameTree');
      const { resource } = await cdp.send('Network.loadNetworkResource', { frameId: frameTree.frame.id, url: href,
        options: { disableCache: false, includeCredentials: true } });
      handle = resource.stream;
      if (!resource.success || !handle || (resource.httpStatusCode ?? 0) >= 400)
        throw Error(`Browser download failed (${resource.httpStatusCode ?? resource.netErrorName ?? 'network error'}).`);
      const headers = new Headers(Object.entries(resource.headers ?? {}).map(([k, v]): [string, string] => [k, String(v)]));
      const disposition = headers.get('content-disposition') ?? '';
      if (headers.get('content-type')?.toLowerCase().includes('text/html') && !/attachment/i.test(disposition))
        throw Error('The site returned an HTML page instead of a file. Check the browser for a sign-in page or use the site’s download link.');
      const encoded = /filename\*=UTF-8''([^;]+)/i.exec(disposition)?.[1];
      const plain = /filename\s*=\s*(?:"([^"]*)"|([^;]*))/i.exec(disposition);
      try { file.name = safeName(encoded ? decodeURIComponent(encoded) : plain?.[1] ?? plain?.[2] ?? decodeURIComponent(file.name)); } catch { /* Keep the safe URL name. */ }
      if (Number(headers.get('content-length')) > DOWNLOAD_BYTES) throw Error('Download exceeds 25 MB.');
      const chunks: Buffer[] = []; let size = 0;
      for (;;) {
        const chunk = await cdp.send('IO.read', { handle, size: 64 * 1024 });
        const bytes = Buffer.from(chunk.data, chunk.base64Encoded ? 'base64' : 'utf8');
        size += bytes.length;
        if (size > DOWNLOAD_BYTES) throw Error('Download exceeds 25 MB.');
        chunks.push(bytes);
        if (chunk.eof) break;
      }
      if (!size) throw Error('The downloaded file is empty.');
      const dest = filePath(user, ward, file.id);
      fs.mkdirSync(path.dirname(dest), { recursive: true, mode: 0o700 });
      fs.writeFileSync(dest, Buffer.concat(chunks), { mode: 0o600, flag: 'wx' });
      file.bytes = size; file.status = 'ready';
    } catch (e) {
      file.status = 'failed'; file.error = e instanceof Error ? e.message.split('\n')[0] : 'Download failed.';
    } finally {
      if (timer) clearTimeout(timer);
      if (handle) await cdp?.send('IO.close', { handle }).catch(() => {});
      await cdp?.detach().catch(() => {});
      save(); active.delete(key);
    }
  });
  active.set(key, pending); save(); void pending.catch(() => {});
  return { ...file };
}

export async function waitDownloads(user: number, ward: string): Promise<void> {
  let timer: ReturnType<typeof setTimeout> | undefined;
  try {
    await Promise.race([Promise.all([...active].filter(([key]) => key.startsWith(prefix(user, ward))).map(([, p]) => p)),
      new Promise(resolve => { timer = setTimeout(resolve, 10_000); timer.unref(); })]);
  } finally { clearTimeout(timer); }
}

export function downloadResponse(user: number, ward: string, id: string): Response {
  if (!/^[a-f0-9-]{36}$/.test(id)) return Response.json({ error: 'Invalid download.' }, { status: 400 });
  const raw = getSetting(keyOf(user, ward, id));
  const file = raw ? JSON.parse(raw) as BrowserDownload : undefined;
  if (file?.status !== 'ready') return Response.json({ error: file?.error ?? 'Download is not ready.' }, { status: 404 });
  try {
    return new Response(fs.readFileSync(filePath(user, ward, id)), { headers: {
      'content-type': 'application/octet-stream', 'content-disposition': `attachment; filename*=UTF-8''${encodeURIComponent(file.name)}`,
      'cache-control': 'private, no-store', 'x-content-type-options': 'nosniff', 'x-rimeward-private': '1',
    } });
  } catch { return Response.json({ error: 'Downloaded file unavailable.' }, { status: 404 }); }
}

export function removeDownload(user: number, ward: string, id: string): void {
  if (!/^[a-f0-9-]{36}$/.test(id)) throw Error('Invalid download.');
  if (active.has(keyOf(user, ward, id))) throw Error('Download is still in progress.');
  fs.rmSync(filePath(user, ward, id), { force: true });
  getDb().prepare('DELETE FROM settings WHERE key=?').run(keyOf(user, ward, id));
}

/** Called after the browser closes, so its final download receipts land before moving/removing the ward. */
export async function moveDownloads(user: number, ward: string, next?: string): Promise<void> {
  await Promise.all([...active].filter(([key]) => key.startsWith(prefix(user, ward))).map(([, p]) => p));
  const source = path.join(ROOT, String(user), ward);
  if (next) {
    if (fs.existsSync(source)) fs.renameSync(source, path.join(ROOT, String(user), next));
    for (const file of listDownloads(user, ward)) getDb().prepare('UPDATE settings SET key=? WHERE key=?')
      .run(keyOf(user, next, file.id), keyOf(user, ward, file.id));
  } else {
    fs.rmSync(source, { recursive: true, force: true });
    getDb().prepare('DELETE FROM settings WHERE key GLOB ?').run(`${prefix(user, ward)}*`);
  }
}
